name: facebook_clone_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0



  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.18.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  auto_size_text: ^3.0.0
  readmore: ^2.2.0
  reaction_askany: ^0.1.2
  get_it: ^7.6.4
  go_router: ^12.0.0
  flutter_riverpod: ^2.4.4
  fpdart: ^1.1.0
  dartz: ^0.10.1
  cloud_firestore: ^4.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  firebase_auth: '4.3.0'
  firebase_auth_platform_interface: '6.15.3'

  
flutter:

  uses-material-design: true

  
  fonts:
    - family: klavika
      fonts:
        - asset: assets\fonts\klavika-bold-italic.otf
          weight: 100
        - asset: assets\fonts\klavika-bold.otf
          weight: 200
        - asset: assets\fonts\klavika-light-italic.otf
          weight: 300
        - asset: assets\fonts\klavika-light.otf
          weight: 400
        - asset: assets\fonts\klavika-medium-italic.otf
          weight: 500
        - asset: assets\fonts\klavika-medium.otf
          weight: 600
        - asset: assets\fonts\klavika-regular-italic.otf
          weight: 700
          
  assets:
      - assets\images\Facebook_Logo_Primary.png
      - assets\images\Facebook_Logo_Secondary.png
      - assets\images\download.jpg
      - assets\images\images.jpg
      - assets\images\IMG20221027193308.jpg
      - assets\icons\facebook_reaction_icons\angry.png
      - assets\icons\facebook_reaction_icons\sad.png
      - assets\icons\facebook_reaction_icons\care.png
      - assets\icons\facebook_reaction_icons\wow.png
      - assets\icons\facebook_reaction_icons\like.png
      - assets\icons\facebook_reaction_icons\haha.png
      - assets\icons\facebook_reaction_icons\love.png
      - assets\images\CJ.jpg
      - assets\images\steve.jpg
      - assets\images\joel.jpg
      - assets\images\dingodile.jpg
      - assets\images\crash.jpg
      - assets\images\default_picture.jpg
