// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1746u14Oo5g2npHOfap68fSffSuJ3DLY',
    appId: '1:744408323416:web:7fc53d9e2e6fe614ea812d',
    messagingSenderId: '744408323416',
    projectId: 'facebook-unes',
    authDomain: 'facebook-unes.firebaseapp.com',
    storageBucket: 'facebook-unes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPlT4RvmbefXV5mlFgHjWZcDfEmOgUrGU',
    appId: '1:744408323416:android:ccc74e4bed508886ea812d',
    messagingSenderId: '744408323416',
    projectId: 'facebook-unes',
    storageBucket: 'facebook-unes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxyz22H88nHfHMXzwAbzAfatFzx53NQJg',
    appId: '1:744408323416:ios:1bc3e24c1e794b20ea812d',
    messagingSenderId: '744408323416',
    projectId: 'facebook-unes',
    storageBucket: 'facebook-unes.appspot.com',
    iosBundleId: 'com.example.facebookCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxyz22H88nHfHMXzwAbzAfatFzx53NQJg',
    appId: '1:744408323416:ios:b393c9317ab28eeeea812d',
    messagingSenderId: '744408323416',
    projectId: 'facebook-unes',
    storageBucket: 'facebook-unes.appspot.com',
    iosBundleId: 'com.example.facebookCloneApp.RunnerTests',
  );
}
